adding tests to verify pdf-git option and its error messages
openstax/output-producer-service pull request #239
Opened 2020-11-20 21:24 UTC by omehes

2020-11-24 16:43 UTC, brittweinstein commented
@omehes please put points on this

2020-11-24 17:18 UTC, tomjw64 requested changes

2020-11-24 17:18 UTC, tomjw64 commented on frontend/pages/index.vue
> +                      <v-radio label="PDF (git)" :value="jobTypes.GIT_PDF" class="git-pdf-radio-button" ></v-radio>
unnecessary change

2020-11-24 17:18 UTC, tomjw64 commented on frontend/pages/index.vue
> +                        class="collection-id-error-text git-pdf-error-text collection-id-incorrect-error-text git-pdf-incorrect-error-text collection-id-field"
additional classes are not needed, we should use the same class for locating the same element, ideally just `collection-id-field` here

2020-11-30 16:05 UTC, omehes commented
@tomjw64 changes you requested are done. ready for another review :)

2020-11-30 16:23 UTC, tomjw64 approved these changes

2020-11-30 16:28 UTC, merged